import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

export async function POST(req: NextRequest) {
    let apiKey = "";
    try {
        const body = await req.json();
        const { text, prompt } = body;
        apiKey = body.apiKey;

        if (!text || !apiKey) {
            return NextResponse.json({ error: "Missing text or API Key" }, { status: 400 });
        }

        const defaultPrompt = `You are an expert viral content scriptwriter. Your task is to take a raw video transcript provided by the user and rewrite it into a specific 3-part format.

The output must be strictly formatted as follows:

1. First, provide a rephrased "Story Version" inside double quotes. This should be a concise, engaging summary of the transcript.
2. Second, provide a "VO Prompt" block with specific metadata (Duration, Voice Style, Tone, Pacing, and a Light/Funny CTA note). Use the specific emojis and formatting shown in the example below.
3. Third, provide the "Script" text. This must be written for a fast-paced, engaging voiceover (approx 20-30 seconds). It must build tension or curiosity and end with a witty, funny, or sarcastic Call to Action (CTA) related to the topic.

**Required Output Format:**

“[Insert Rephrased Story Version Here]”

🎙️ **Google AI Studio VO Prompt ([Insert Approx Time], [Insert Style] + Funny CTA)**
**Voice Style:** [e.g. Fast, suspenseful, storytelling]
**Tone:** [e.g. Serious but engaging, investigative]
**Pacing:** [e.g. Quick buildup → reveal → impact]
**CTA:** Light, funny

**Script:**

“[Insert Script Text Here. Make it punchy. End with a specific funny CTA related to the story.]”

**Rules:**
- Do not add any conversational filler before or after the output.
- The Script must be distinct from the Story Version (optimized for speaking rhythm).
- The CTA must be a joke or a witty observation, not just "Please subscribe."
- IMPORTANT: You must strictly follow the sequence of events narrated in the script in the same manner. Do not reorder events.`;

        const systemPrompt = prompt || defaultPrompt;

        // Initialize Google Generative AI
        const genAI = new GoogleGenerativeAI(apiKey);

        // Use gemini-2.0-flash model as it is available for this user
        const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

        const fullPrompt = `${systemPrompt}\n\nText to rephrase:\n${text}`;

        const result = await model.generateContent(fullPrompt);
        const response = await result.response;
        const rephrasedText = response.text();

        if (!rephrasedText) {
            return NextResponse.json({ error: "No content generated by Gemini" }, { status: 500 });
        }

        return NextResponse.json({ rephrasedText });

    } catch (error: any) {
        console.error("Rephrase API Error:", error);

        // Debug: List available models if generation fails
        try {
            const listModelsResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`);
            const listModelsData = await listModelsResponse.json();
            console.log("Available Models:", JSON.stringify(listModelsData, null, 2));

            if (listModelsData.models) {
                const modelNames = listModelsData.models.map((m: any) => m.name);
                return NextResponse.json({
                    error: `Model not found. Available models: ${modelNames.join(", ")}`,
                    details: error.message
                }, { status: 500 });
            }
        } catch (listError) {
            console.error("Failed to list models:", listError);
        }

        return NextResponse.json({ error: error.message || "An error occurred with Gemini API" }, { status: 500 });
    }
}
